version: "3"
services:
  app:
    container_name: webauthntest
    image: webauthntest
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017/
      - JWT_SECRET=${JWT_SECRET}
      - HOSTNAME=${HOSTNAME}
      - VIRTUAL_HOST=${HOSTNAME}
      - VIRTUAL_PORT=3000
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  proxy:
    container_name: proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - //var/run/docker.sock:/tmp/docker.sock:ro

    
